### ISSUE TITLE
Route Analysis

### ISSUE THREAD

**Issue by dhawton** [rahulp959/vattrack.web#22]

**Comment by rahulp959** [comment]
Route analysis? In what sense?

**Comment by dhawton** [comment]
IFR Route analysis.. ie, flightaware's route analysis

**Comment by rahulp959** [comment]
http://uk.flightaware.com/analysis/route.rvt?origin=kord&destination=kmci

Do you mean similar to this?

**Comment by dhawton** [comment]
Yes.  The API portion is mostly written, there are a couple fields I need to add and will develop this tomorrow. http://api.airstats.org/Routes/KLAX/KLAS

**Comment by dhawton** [comment]
PR #42
